name: test_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Sürüm aralığını genelleştirdim, hata almanı engeller

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # --- KAMERA VE İZİNLER ---
  camera: ^0.10.5
  permission_handler: ^11.0.1

  # --- YAPAY ZEKA (YOLO) ---
  # YOLO modellerini (v5/v8) çalıştırmak için en iyi kütüphane budur.
  # Eski 'tflite_flutter' yerine bunu kullanacağız.
  flutter_vision: ^1.1.4

  # Eski kütüphanelere artık ihtiyacımız yok (Yorum satırı yaptım veya silebilirsin)
  # tflite_flutter: ^0.9.1 
  # image: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # --- DOSYA YOLLARI ---
  assets:
    # İndirdiğin yeni model dosyasının tam adı
    - assets/models/best_float16.tflite
    # Oluşturduğun etiket dosyası
    - assets/models/labels.txt
    
  # Fontlar (Senin dosyanı korudum)
  fonts:
    - family: MyFont
      fonts:
        - asset: assets/fonts/MomoSignature-Regular.ttf
          weight: 700